site_name: clara-agent
repo_url: https://github.com/Cellular-Semantics/clara-agent
site_url: https://Cellular-Semantics.github.io/clara-agent
site_description: CLARA is an agentic pipeline that verifies Cell Ontology term definitions against referenced literature to support accurate, reliable curation.
site_author: Cellular-Semantics
edit_uri: edit/main/docs/
repo_name: Cellular-Semantics/clara-agent
copyright: Maintained by <a href="https://Cellular-Semantics.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Cellular-Semantics/clara-agent
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/clara-agent

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
